export const CHANGE_INPUT = 'CHANGE_INPUT'
export const ADD_SITE = 'ADD_SITE'
export const REMOVE_SITE = 'REMOVE_SITE'
export const ADD_STAGE = 'ADD_STAGE'
export const REMOVE_STAGE = 'REMOVE_STAGE'
export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
